name: ACR Multi-Arch Build and Push

permissions:

  contents: write

on:
  push:
    # Only run this workflow when a tag starting with 'v' is pushed
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # The name of the repository/image within ACR.
  IMAGE_REPO_NAME: airspace-link-inc/dji-log-parser-fork
  # Set the desired platforms
  PLATFORMS: linux/amd64,linux/arm64,darwin/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GitHub Packages (ghcr.io)

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v5

      - name: 🐳 Docker Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔨 Set up QEMU
        # Required to run emulation for ARM/other architectures
        uses: docker/setup-qemu-action@v3

      - name: 🏗️ Set up Docker Buildx
        # Enables multi-arch builds
        uses: docker/setup-buildx-action@v3

      - name: 🏷️ Define Image Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO_NAME }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}

      - name: 🚀 Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile 
          push: true
          provenance: mode=min # use min for now since max could store some build env vars
          sbom: true # Generate SBOM
          tags: ${{ steps.meta.outputs.tags }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha # Use GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max
          secrets: |
            "asl_gha_user=${{ secrets.asl_gha_pat }}"
            "asl_pipeline_read_packages_token=${{ secrets.asl_pipeline_read_packages_token }}"

